current_instance kv260_video_i/PS_VIDEO/RX_VIDEO/ila_0/U0
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_CDONE/I_YESLUT6.U_SRL32_*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_CDONE/I_YESLUT6.I_YES_OREG.O_reg_reg*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_NS1/I_YESLUT6.U_SRL32_*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_NS1/I_YESLUT6.I_YES_OREG.O_reg_reg*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_NS0/I_YESLUT6.U_SRL32_*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_NS0/I_YESLUT6.I_YES_OREG.O_reg_reg*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/U_WCE/I_YESLUT6.U_SRLC16E*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/iwcnt_reg[*]*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/U_SCE/I_YESLUT6.U_SRLC16E*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/iscnt_reg[*]*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/U_SCMPCE/I_YESLUT6.U_SRL32*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/u_scnt_cmp_q*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/U_WHCMPCE/I_YESLUT6.U_SRL32*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/u_wcnt_hcmp_q*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/U_WLCMPCE/I_YESLUT6.U_SRL32*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/u_wcnt_lcmp_q*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
create_waiver -type CDC -id {CDC-10} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/DUT/I_WHOLE_SLICE.G_SLICE_IDX[*].U_ALL_SRL_SLICE/u_srl*/S*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/DUT/I_WHOLE_SLICE.G_SLICE_IDX[*].U_ALL_SRL_SLICE/I_IS_TERMINATION_SLICE_W_OUTPUT_REG.DOUT_O_reg*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
create_waiver -type CDC -id {CDC-10} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/U_SCE/I_YESLUT6.U_SRLC16E*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/icap_wr_en_reg*"}]] -timestamp "Mon Jun  6 16:27:58 GMT 2022"
current_instance -quiet
set_property DATA_RATE DDR [get_ports mipi_phy_if_0_clk_p]
set_property DATA_RATE DDR [get_ports mipi_phy_if_0_clk_n]
set_property DATA_RATE DDR [get_ports {mipi_phy_if_0_data_p[0]}]
set_property DATA_RATE DDR [get_ports {mipi_phy_if_0_data_n[0]}]
set_property DATA_RATE DDR [get_ports {mipi_phy_if_0_data_p[1]}]
set_property DATA_RATE DDR [get_ports {mipi_phy_if_0_data_n[1]}]
set_property PACKAGE_PIN D7 [get_ports mipi_phy_if_0_clk_p]
set_property PACKAGE_PIN D6 [get_ports mipi_phy_if_0_clk_n]
set_property PACKAGE_PIN E5 [get_ports {mipi_phy_if_0_data_p[0]}]
set_property PACKAGE_PIN D5 [get_ports {mipi_phy_if_0_data_n[0]}]
set_property PACKAGE_PIN G6 [get_ports {mipi_phy_if_0_data_p[1]}]
set_property PACKAGE_PIN F6 [get_ports {mipi_phy_if_0_data_n[1]}]
current_instance kv260_video_i/PS_VIDEO/VIDEO_PIPELINE/ila_1/U0
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_CDONE/I_YESLUT6.U_SRL32_*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_CDONE/I_YESLUT6.I_YES_OREG.O_reg_reg*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_NS1/I_YESLUT6.U_SRL32_*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_NS1/I_YESLUT6.I_YES_OREG.O_reg_reg*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_NS0/I_YESLUT6.U_SRL32_*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/U_NS0/I_YESLUT6.I_YES_OREG.O_reg_reg*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/U_WCE/I_YESLUT6.U_SRLC16E*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/iwcnt_reg[*]*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/U_SCE/I_YESLUT6.U_SRLC16E*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/iscnt_reg[*]*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/U_SCMPCE/I_YESLUT6.U_SRL32*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/u_scnt_cmp_q*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/U_WHCMPCE/I_YESLUT6.U_SRL32*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/u_wcnt_hcmp_q*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/U_WLCMPCE/I_YESLUT6.U_SRL32*"}]] -to [get_pins -filter REF_PIN_NAME=~CE -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_window_counter/u_wcnt_lcmp_q*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
create_waiver -type CDC -id {CDC-10} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/DUT/I_WHOLE_SLICE.G_SLICE_IDX[*].U_ALL_SRL_SLICE/u_srl*/S*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/DUT/I_WHOLE_SLICE.G_SLICE_IDX[*].U_ALL_SRL_SLICE/I_IS_TERMINATION_SLICE_W_OUTPUT_REG.DOUT_O_reg*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
create_waiver -type CDC -id {CDC-10} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1037291" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/u_cap_sample_counter/U_SCE/I_YESLUT6.U_SRLC16E*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*u_ila_cap_ctrl/u_cap_addrgen/icap_wr_en_reg*"}]] -timestamp "Mon Jun  6 16:28:07 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/V_DMA/axi_vdma_0/U0
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.ip2axi_rddata_captured_mm2s_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.ip2axi_rddata_captured_s2mm_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. This value changes only on frame boundaries." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_MM2S_LITE_CROSSINGS.GEN_MM2S_CROSSINGS_ASYNC.mm2s_ip2axi_frame_ptr_ref_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. This value changes only on frame boundaries." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_MM2S_LITE_CROSSINGS.GEN_MM2S_CROSSINGS_ASYNC.mm2s_ip2axi_frame_store_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. This value changes only on frame boundaries." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_S2MM_LITE_CROSSINGS.GEN_S2MM_CROSSINGS_ASYNC.s2mm_ip2axi_frame_ptr_ref_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. This value changes only on frame boundaries." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_S2MM_LITE_CROSSINGS.GEN_S2MM_CROSSINGS_ASYNC.s2mm_ip2axi_frame_store_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.axi2ip_rdaddr_captured_mm2s_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.axi2ip_rdaddr_captured_s2mm_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.axi2ip_wraddr_captured_mm2s_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.axi2ip_wraddr_captured_s2mm_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.mm2s_axi2ip_wrdata_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "axi_vdma" -desc "The CDC-1 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.mm2s_axi2ip_wrdata_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-4} -user "axi_vdma" -desc "The CDC-4 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.s2mm_axi2ip_wrdata_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
create_waiver -type CDC -id {CDC-1} -user "axi_vdma" -desc "The CDC-1 warning is waived as it is safe in the context of AXI VDMA. The Address and Data value do not change until AXI transaction is complete." -tags "9601" -scope -internal -to [get_pins -hier -quiet -filter {NAME =~*AXI_LITE_REG_INTERFACE_I/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_LITE_IS_ASYNC.GEN_ASYNC_LITE_ACCESS.s2mm_axi2ip_wrdata_cdc_tig_reg[*]/D}] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
current_instance -quiet
set_property PACKAGE_PIN F10 [get_ports IIC_0_0_sda_io]
set_property PACKAGE_PIN G11 [get_ports IIC_0_0_scl_io]
set_property PACKAGE_PIN F11 [get_ports {rpi_enb[0]}]
current_instance kv260_video_i/PS_VIDEO/RX_VIDEO/mipi_csi2_rx_subsyst_0/U0/phy/inst
create_waiver -type CDC -id {CDC-10} -user "mipi_dphy" -desc "Waiving the CDC-10 as it will not cause any issue as the IBUFDS LPRX port driven by a constant" -tags "1047195" -scope -internal -to [get_pins -hier *s_level_out_d1_cdc_to_reg/D] -timestamp "Mon Jun  6 16:28:08 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/RX_VIDEO/mipi_csi2_rx_subsyst_0/U0/rx/inst/gen_pkt_fifo/pkt_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Mon Jun  6 16:28:10 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/RX_VIDEO/mipi_csi2_rx_subsyst_0/U0/rx/inst/AXI_LITE.reg_inf/gen_spkt_fifo/generic_pkt/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Mon Jun  6 16:28:10 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/RX_VIDEO/mipi_csi2_rx_subsyst_0/U0/rx/inst/AXI_LITE.reg_inf/gen_spkt_fifo/generic_pkt/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Mon Jun  6 16:28:10 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/RX_VIDEO/mipi_csi2_rx_subsyst_0/U0/rx/inst/gen_pkt_fifo/pkt_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Mon Jun  6 16:28:10 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/VIDEO_PIPELINE/v_axi4s_vid_out_0/inst/COUPLER_INST/generate_async_fifo.FIFO_INST/XPM_FIFO_ASYNC_INST/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Mon Jun  6 16:28:10 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/VIDEO_PIPELINE/v_axi4s_vid_out_0/inst/COUPLER_INST/generate_async_fifo.FIFO_INST/XPM_FIFO_ASYNC_INST/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Mon Jun  6 16:28:10 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/VIDEO_PIPELINE/v_axi4s_vid_out_0/inst/COUPLER_INST/generate_async_fifo.FIFO_INST/XPM_FIFO_ASYNC_INST/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Mon Jun  6 16:28:10 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/RX_VIDEO/mipi_csi2_rx_subsyst_0/U0/rx/inst/AXI_LITE.isr_cdc/ecc_cdc
create_waiver -type CDC -id {CDC-15} -user "xpm_cdc" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -tags "1009444" -scope -internal -from [get_pins -quiet src_hsdata_ff_reg*/C] -to [get_pins -quiet dest_hsdata_ff_reg*/D] -timestamp "Mon Jun  6 16:28:10 GMT 2022"
current_instance -quiet
current_instance kv260_video_i/PS_VIDEO/RX_VIDEO/mipi_csi2_rx_subsyst_0/U0/rx/inst/AXI_LITE.reg_inf/img_info_cdc
create_waiver -type CDC -id {CDC-15} -user "xpm_cdc" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -tags "1009444" -scope -internal -from [get_pins -quiet src_hsdata_ff_reg*/C] -to [get_pins -quiet dest_hsdata_ff_reg*/D] -timestamp "Mon Jun  6 16:28:10 GMT 2022"
current_instance -quiet
current_instance dbg_hub/inst
create_waiver -type CDC -id {CDC-6} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD2/stat_reg_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD2/stat_reg_1_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-6} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD3/stat_reg_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD3/stat_reg_1_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-6} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_WR/U_WR_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.wr_pntr_gc_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_WR/U_WR_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*.gsync_stage[1].rd_stg_inst/Q_reg_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-6} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_RD/U_RD_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.wr_pntr_gc_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_RD/U_RD_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*.gsync_stage[1].rd_stg_inst/Q_reg_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-6} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_WR/U_WR_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_WR/U_WR_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*.gsync_stage[1].wr_stg_inst/Q_reg_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-6} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_RD/U_RD_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_RD/U_RD_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*.gsync_stage[1].wr_stg_inst/Q_reg_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-6} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD7_STAT/stat_reg_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD7_STAT/stat_reg_1_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_RD/U_RD_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gdm.dm_gen.dm/RAM_reg*/RAM*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ *U_RD_FIFO*gdm.dm_gen.dm*/gpr1.dout_i_reg*}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~CLK -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_WR/U_WR_FIFO/SUBCORE_FIFO.xsdbm_v3_0_0_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gdm.dm_gen.dm/RAM_reg*/RAM*"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ *U_WR_FIFO*gdm.dm_gen.dm*/gpr1.dout_i_reg*}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD1/ctl_reg_reg[0]"}]] -to [get_pins -filter REF_PIN_NAME=~R -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD4/shift_reg_in_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD1/ctl_reg_reg[0]"}]] -to [get_pins -filter REF_PIN_NAME=~R -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD5/shift_reg_in_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD1/ctl_reg_reg[0]"}]] -to [get_pins -filter REF_PIN_NAME=~R -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD7_CTL/shift_reg_in_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD1/shift_reg_in_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD1/ctl_reg_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD4/shift_reg_in_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD4/ctl_reg_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD5/shift_reg_in_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD5/ctl_reg_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD7_CTL/shift_reg_in_reg[0]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD7_STAT/stat_reg_reg[0]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD7_CTL/shift_reg_in_reg[*]"}]] -to [get_pins -filter REF_PIN_NAME=~D -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD7_CTL/ctl_reg_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
create_waiver -type CDC -id {CDC-15} -user "xsdbm" -desc "CDC is handled through handshake process" -tags "1025927" -scope -internal -from [get_pins -filter REF_PIN_NAME=~C -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/rddata_rst_reg"}]] -to [get_pins -filter REF_PIN_NAME=~CLR -of_objects [get_cells -hierarchical -filter {NAME =~ "*BSCANID.u_xsdbm_id/CORE_XSDB.UUT_MASTER/U_ICON_INTERFACE/U_CMD6_RD/shift_reg_in_reg[*]"}]] -timestamp "Mon Jun  6 16:30:01 GMT 2022"
current_instance -quiet
set_property DIRECTION IN [get_ports {mipi_phy_if_0_data_n[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {mipi_phy_if_0_data_n[1]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_0_data_n[1]}]
set_property EQUALIZATION EQ_NONE [get_ports {mipi_phy_if_0_data_n[1]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {mipi_phy_if_0_data_n[1]}]
set_property LVDS_PRE_EMPHASIS FALSE [get_ports {mipi_phy_if_0_data_n[1]}]
set_property DIRECTION IN [get_ports {mipi_phy_if_0_data_n[0]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {mipi_phy_if_0_data_n[0]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_0_data_n[0]}]
set_property EQUALIZATION EQ_NONE [get_ports {mipi_phy_if_0_data_n[0]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {mipi_phy_if_0_data_n[0]}]
set_property LVDS_PRE_EMPHASIS FALSE [get_ports {mipi_phy_if_0_data_n[0]}]
set_property DIRECTION IN [get_ports {mipi_phy_if_0_data_p[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {mipi_phy_if_0_data_p[1]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_0_data_p[1]}]
set_property EQUALIZATION EQ_NONE [get_ports {mipi_phy_if_0_data_p[1]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {mipi_phy_if_0_data_p[1]}]
set_property LVDS_PRE_EMPHASIS FALSE [get_ports {mipi_phy_if_0_data_p[1]}]
set_property DIRECTION IN [get_ports {mipi_phy_if_0_data_p[0]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {mipi_phy_if_0_data_p[0]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_0_data_p[0]}]
set_property EQUALIZATION EQ_NONE [get_ports {mipi_phy_if_0_data_p[0]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {mipi_phy_if_0_data_p[0]}]
set_property LVDS_PRE_EMPHASIS FALSE [get_ports {mipi_phy_if_0_data_p[0]}]
set_property DIRECTION IN [get_ports mipi_phy_if_0_clk_n]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports mipi_phy_if_0_clk_n]
set_property DIFF_TERM TRUE [get_ports mipi_phy_if_0_clk_n]
set_property EQUALIZATION EQ_NONE [get_ports mipi_phy_if_0_clk_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports mipi_phy_if_0_clk_n]
set_property LVDS_PRE_EMPHASIS FALSE [get_ports mipi_phy_if_0_clk_n]
set_property DIRECTION IN [get_ports mipi_phy_if_0_clk_p]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports mipi_phy_if_0_clk_p]
set_property DIFF_TERM TRUE [get_ports mipi_phy_if_0_clk_p]
set_property EQUALIZATION EQ_NONE [get_ports mipi_phy_if_0_clk_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports mipi_phy_if_0_clk_p]
set_property LVDS_PRE_EMPHASIS FALSE [get_ports mipi_phy_if_0_clk_p]
set_property DIRECTION INOUT [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_scl_io]
set_property DRIVE 12 [get_ports IIC_0_0_scl_io]
set_property SLEW SLOW [get_ports IIC_0_0_scl_io]
set_property PULLUP true [get_ports IIC_0_0_scl_io]
set_property DIRECTION INOUT [get_ports IIC_0_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_sda_io]
set_property DRIVE 12 [get_ports IIC_0_0_sda_io]
set_property SLEW SLOW [get_ports IIC_0_0_sda_io]
set_property PULLUP true [get_ports IIC_0_0_sda_io]
set_property DIRECTION OUT [get_ports {rpi_enb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rpi_enb[0]}]
set_property DRIVE 12 [get_ports {rpi_enb[0]}]
set_property SLEW SLOW [get_ports {rpi_enb[0]}]
#revert back to original instance
current_instance -quiet
